#!/bin/bash
TMPFILE=".gmpl.tmp"
OUTDIR="../../public/gmpl"
python pre_process_test.py

# Pre-process texinfo file
python pre_process.py > $TMPFILE

# Use makeinfo to turn pre-processed file into HTML files
makeinfo --html $TMPFILE --css-ref=../../lib/ui-bootstrap/bootstrap.css --css-include=custom.css -o $OUTDIR

# Do some post-processing
find $OUTDIR | grep '\.html$' | xargs -L 1 sed -i -e 's/<a name="/<a class="anchor" name="/g' 

